repos:
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args: [--target-version=py37]
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    args:
      # default black line length is 88
      - --max-line-length=88
      # black may include space before :
      # black breaks before binary operator
      - --ignore=E203,W503
